spring.application.name=honeymoney

# Base de datos en memoria
spring.datasource.url=jdbc:h2:mem:honeymoney
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000

# SpringDoc
springdoc.writer-with-default-pretty-printer=true

# credenciales Spring Security
spring.security.user.password = e0ff3644-7bed-4e7d-a556-dcfceb12ac3a
spring.security.user.name = camss