spring.application.name=honeymoney

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:libreria
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecto de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2 (opcional pero muy útil)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console